### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by buep** [Praqma/staci#27]
To start with I would very much like to know:
- how do I get it up and running?
- how do I input a license

Think a lot of it is explained here: http://www.praqma.com/stories/staci/ but is should also be together with the code.

**Comment by hoeghh** [comment]
There is a section in the readme.md called getting startede. IT will, hopfully get you startet. We wanted to create a wiki, but havnt had the time yet to add text.

**Comment by buep** [comment]
Okay, I see it. That is an okay start.

Make this issue about how to manage licenses for Atlassian if we have any thoughts on it. 
And incorporate all the nice things mentioned in the Praqma Story about Staci into the readme.

I suggest to consider not to use a wiki - keep documentation together with the code, instead of "on the side" as a wiki will be.

**Comment by martinmosegaard** [comment]
Some work has been done to improve the readme. Closing this issue, then we can open more specific issues as the need arises.
