### ISSUE TITLE
Report all runtime information into a markdown file

### ISSUE THREAD

**Issue by buep** [Praqma/staci#3]
It would be great if all the information I needed after starting STACI was reported into a markdown file (or other easily readable format) so everything is at hand when needed.

Usernames, passwords, URLs, information to use for configuration and so.

It could be instead of printing to the terminal, or we could do both. It could also be a configuration option:
printSummaryToTerminal: true
printSummaryToFile: true

**Comment by hoeghh** [comment]
As i wrote in issue #5, i was thinking of writing it to a html file, to open in your favorite browser.

**Comment by hoeghh** [comment]
Added with 95a7350c389bcaba1a9227d1cdf196d035d2f7f3 in html file that opens upon install
