### ISSUE TITLE
Delete obsolete scripts

### ISSUE THREAD

**Issue by martinmosegaard** [Praqma/staci#30]
After introducing the staci.sh script, which uses functions/staciOperations.f, it seems that install.sh, start.sh, stop.sh, setEnv.sh, removeContainers.sh are obsolete.

Make sure they are, by comparing them with staciOperations.f, then delete them.

**Comment by hoeghh** [comment]
fixed with 0b3cc9e9909d2cda5ed47cd40c5dddc8cd3df7ec
