### ISSUE TITLE
Use DNS names instead of IPs

### ISSUE THREAD

**Issue by buep** [Praqma/staci#4]
Currently IP addresses are used, which makes it hard to move things around and use them on other networks.

We should abstract IP addresses to use DNS names instead.
Either using directory service, DNS service or provide few lines need in a host file.

**Comment by hoeghh** [comment]
Yes, i think we need to add a hostname to staci.properties. Right now i get every ip from the DOCKER_HOST variable. Thats not very smart. So, good idear :)

**Comment by hoeghh** [comment]
So, with the commit 9f45cdc329c2b0b0fc24d1bf7b9c6ff1780d71ae when using cluster and a provider, we now have overlay networking. And now you can use the names of the hosts and containers instead of ip's.

So when setting up database for Jira, use atlassiandb as hostname for the database connection.
