### ISSUE TITLE
Post configuration should be described

### ISSUE THREAD

**Issue by buep** [Praqma/staci#5]
After starting STACI there was a lot of post configuration to do. Settings up usernames, licenses, application links etc.

I would like all these steps to be described in a post-configuration-todo-file, that we maintain together with the code.

Then as we improve the setup and post configuration this file will get smaller.

When we have the file, we can also use it as inputs for the new issues for the things we want to improve first.

**Comment by hoeghh** [comment]
I was thinking about generating a html file with all needed information, istead of printing to cli. Then call your favorite browser (dependent on issue #7) with the html file.

**Comment by buep** [comment]
Might be an even better idea :-)

**Comment by buep** [comment]
Might be an even better idea :-)

**Comment by buep** [comment]
Might be an even better idea :-)

**Comment by hoeghh** [comment]
With 95a7350c389bcaba1a9227d1cdf196d035d2f7f3 i now open the browser and displays the System Informations html page.
