### ISSUE TITLE
Failure with initial MySQL setup 

### ISSUE THREAD

**Issue by JKrag** [Praqma/staci#50]
I am trying to spin up a new staci env. with Bamboo, Bitbucket and mysql.
It seems to start up fine, but when I log into Bamboo and try to configure the DB connection using the credentials mentioned in the SystemInfo.html page, I run into problems.

First it informs me that MySQL driver is no longer installed by default, and I have to install that myself. I haven't verified whether the driver is actually already in the Staci image though.

If I proceed to the actual DB config page, I get the following error:

`Error accessing database: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.`

On the surface at least, this doesn't look like a missing driver problem. I am assuming that the actual connection attempts indicate a working driver, but I might be mistaken?

**Comment by JKrag** [comment]
<img width="977" alt="choose_how_you_wish_bamboo_to_connect_to_your_database_-_atlassian_bamboo" src="https://cloud.githubusercontent.com/assets/1712950/15891297/31b36928-2d74-11e6-8d97-5408f63139c4.png">

**Comment by hoeghh** [comment]
Whats in your $STACI_HOME/logs/mysqlInit.log file?
The driver should be in the images. But maybe the mysql container did not start, or could not prepare it.
Is mySQL running (the container)

**Comment by hoeghh** [comment]
I will look at it later, but for now try this:

cd staci
export STACI_HOME=$(pwd)
source functions/tools.f 
./bin/init-mysql.sh 

And then try test connection.

**Comment by JKrag** [comment]
mysqlInit.log file only has the following:

`Warning: Using a password on the command line interface can be insecure.`

**Comment by JKrag** [comment]
Also from my staci install:

```
➜  staci git:(master) ./staci.sh install
 - Running dependency checks, please wait...
  - Docker version      : 1.11.1 - OK
  - Docker-compose version  : 1.7.1  - OK
  - Docker-machine version  : 0.7.0  - OK
Installing using property files, please wait....
  - Creating instance praqma-Atlassian via virtualbox - tail -f /Users/jankrag/github/Praqma/staci/logs/virtualbox.praqma-Atlassian.log

 - Building images
  # Building base image, please wait...
    - Building base image.
  # Building Atlassian, please wait...
   - Building Bamboo image
   - Building Bitbucket image
   - Building MySQL image
 - Generating docker-compose.yml - OK
 - Starting containers, using docker-compose
 - Container mysql is active, waiting to be ready
 - MySQL is up!
 - Setting up MySQL for Bamboo

 - Install type : Production install
 - Select database : External MySQL
 - Connection : Direct JDBC
 - Database URL : jdbc:mysql://atlassiandb/bamboodb?autoReconnect=true
 - User name : bamboouser
 - Password : bamboopass
 - Overwrite Existing data : Yes, if you want

 - Setting up MySQL for Bitbucket

 - Database : External
 - Database type : MySQL
 - Hostname : atlassiandb
 - Port : 3306
 - Database name : bitbucketdb
 - Database username : bitbucketdbuser
 - Database password : bitbucketpass

Install complete
Open /Users/jankrag/github/Praqma/staci/SystemInfo.html in a browser to continue using the tool stack
```

**Comment by hoeghh** [comment]
Looks good. Are you running on Linux og Mac? It seems as if you bamboo container cant ping your atlassiandb container. Could you try and exec -it bash into your bamboo and ping atlassiandb ?

**Comment by JKrag** [comment]
I am currently running on Mac, with provider_type:Virtualbox as I couldn't get it to run using `none` (in an attempt to run against my "Docker for Mac beta"). 

Docker ps inside my boot2docker virtualbox image reports:

```
docker@praqma-Atlassian:~$ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                                              NAMES
9173fbc1ad0d        staci/bitbucket:0.1     "/opt/atlassian/bitbu"   21 hours ago        Up 2 hours          0.0.0.0:7990->7990/tcp, 0.0.0.0:7999->7999/tcp     bitbucket
f94e0d491e1d        staci/atlassiandb:0.1   "/entrypoint.sh mysql"   21 hours ago        Up 2 hours          0.0.0.0:3306->3306/tcp                             atlassiandb
473636ec9b58        staci/bamboo:0.1        "/srv/bamboo.sh serve"   21 hours ago        Up 2 hours          0.0.0.0:8085->8085/tcp, 0.0.0.0:54663->54663/tcp   bamboo
```

I will try the ping now.

**Comment by JKrag** [comment]
```
docker@praqma-Atlassian:~$ docker exec -it bamboo /bin/bash
atlassian@bamboo:~$ ping atlassiandb
PING atlassiandb (172.18.0.4): 56 data bytes
64 bytes from 172.18.0.4: icmp_seq=0 ttl=64 time=0.067 ms
64 bytes from 172.18.0.4: icmp_seq=1 ttl=64 time=0.071 ms
64 bytes from 172.18.0.4: icmp_seq=2 ttl=64 time=0.065 ms
^C--- atlassiandb ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.065/0.068/0.071/0.000 ms
atlassian@bamboo:~$ 
```

I assume this should be enough, or does Bamboo also need it to be accessible via the VB machines ip?

**Comment by hoeghh** [comment]
Looks fine. Does bitbucket work?

**Comment by JKrag** [comment]
Bitbucket starts, but I haven't quite figured out which user credentials to use to log in. Maybe I messed up something yesterday while trying to get the whole thing working. Is there an equivalent  of something like a `./staci.sh reset` that just resets all data without having to rebuild the actual images?

**Comment by hoeghh** [comment]
If you delete the volume folders on your host, and start ./staci.sh install again you will start over.

I have just tried bamboo on my machine, and it works. 
Remember, if you restart, to delete the content of atlassiandb folder as well. 

If you need to stop the containers, use ./staci.sh stop, and then ./staci.sh start next time they should be started again.

**Comment by martinmosegaard** [comment]
I have the same problem. It seems that neither databases or database users are created. If I test connection with the root DB user, I get the error `Unknown database 'jiradb'` instead.

This does not seem Mac specific.

**Comment by JKrag** [comment]
@hoeghh : I tried your suggestion with running init-mysql locally. It fails with TLS connection problems:

```
➜  staci git:(master) export STACI_HOME=$(pwd)
➜  staci git:(master) source functions/tools.f 
➜  staci git:(master) ./bin/init-mysql.sh
 - Setting up MySQL for Bamboo
Error checking TLS connection: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  : 

Error checking TLS connection: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  : 

Error checking TLS connection: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  : 


 - Install type : Production install
 - Select database : External MySQL
 - Connection : Direct JDBC
 - Database URL : jdbc:mysql://atlassiandb/bamboodb?autoReconnect=true
 - User name : bamboouser
 - Password : bamboopass
 - Overwrite Existing data : Yes, if you want

 - Setting up MySQL for Bitbucket
Error checking TLS connection: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  : 

Error checking TLS connection: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  : 

Error checking TLS connection: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  : 


 - Database : External
 - Database type : MySQL
 - Hostname : atlassiandb
 - Port : 3306
 - Database name : bitbucketdb
 - Database username : bitbucketdbuser
 - Database password : bitbucketpass
```

I would try to do a `docker-machine regerate-certs`but right now my system is still in the middle of trying to set up the servers with embedded databases, and I don't want to reboot my VB in the middle of that.

**Comment by hoeghh** [comment]
I have made changes with issue #51 
Could you please test this? Start over, and see if it works.

**Comment by JKrag** [comment]
I tried starting over with the newest code changes, and it seems everything works fine now, so thanks a lot.
