### ISSUE TITLE
Bitbucket error

### ISSUE THREAD

**Issue by timea** [Praqma/staci#53]
The installation run without error

![image](https://cloud.githubusercontent.com/assets/4135651/16832909/ec8e2e3c-49ac-11e6-9602-fc6e335c22fb.png)

But then 

![image](https://cloud.githubusercontent.com/assets/4135651/16832893/cbf6751c-49ac-11e6-917c-444caffb323d.png)

It is on 
Ubuntu 16.04 with
- Docker version      : 1.11.2 - OK
- Docker-compose version  : 1.6.2  - OK
- Docker-machine version  : 0.7.0  - OK

**Comment by hoeghh** [comment]
Same as jira error.

**Comment by hoeghh** [comment]
This is becourse volume_dir in $STACI_HOME/conf/staci.properties is set to a place where your user does not have write access. Set volume_dir to a folder in your home folder. Like /home/hoeghh/atlassian and try again.

**Comment by timea** [comment]
From Henrik: "We are planning on implementing a check, that checks if the volumes are writable or not, and give a nice output if not"
