### ISSUE TITLE
Jira error

### ISSUE THREAD

**Issue by timea** [Praqma/staci#54]
Installation run without an error

![image](https://cloud.githubusercontent.com/assets/4135651/16833069/dc5e504a-49ad-11e6-9235-4ccbf02a4647.png)

But then

![image](https://cloud.githubusercontent.com/assets/4135651/16833054/c9694846-49ad-11e6-94f2-30a2aae06b0e.png)

It is on 
Ubuntu 16.04 with

Docker version : 1.11.2 - OK
Docker-compose version : 1.6.2 - OK
Docker-machine version : 0.7.0 - OK

**Comment by hoeghh** [comment]
The user with uid 1000 tried to write data to the volumen folder you specified in staci.properties, but does not have the rights to do so. Im Still in Holland, so i cant help More before Im home again.

**Comment by timea** [comment]
Please do not worry about it now, it was just for reference :) We talk when you are back :)

**Comment by timea** [comment]
From Henrik: "We are planning on implementing a check, that checks if the volumes are writable or not, and give a nice output if not"
