### ISSUE TITLE
Volumes from containers

### ISSUE THREAD

**Issue by buep** [Praqma/staci#6]
We should mount volumes on the hosts, they should be data containers. That is the recommended way of using docker currently as far as I know.

It could also make it easier to migrate?

**Comment by hoeghh** [comment]
The problem right now is, at as of Docker 1.8 theres no User namespace mapping from host to container. They have it planned for 1.9. Then it makes alot of sence. Right now you have to do a hack to get it to work with other users then root.

https://github.com/docker/docker/wiki/Engine-1.9.0

**Comment by buep** [comment]
okay, then lets wait

**Comment by hoeghh** [comment]
Volumes from should not be used. When running STACI locally, volumes on host filesystem can be used, but on a cluster (with use of a provider) we should support Flocker or alike : https://clusterhq.com/flocker/introduction/
