### ISSUE TITLE
Start my browser

### ISSUE THREAD

**Issue by buep** [Praqma/staci#7]
It would be great with a script or configuration option that fires up all the systems in a new tab in a browser of choice.

Eg.

./start-my-browser.sh firefox|chrome|safari

will run the command on the system firefox with paramteres needed to open all our URLs.

**Comment by hoeghh** [comment]
Sounds very smart. I'll look into that. 
And add elinks to the list :)

**Comment by hoeghh** [comment]
Added in 95a7350c389bcaba1a9227d1cdf196d035d2f7f3
