### ISSUE TITLE
All tools under same port, different context.

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/staci#72]
I find it unintuitive that there seem to be both a port difference and context difference when installing the tools.
Could it be advisable with a Nginx/apache up-front to collect them all under normal port 80?

**Comment by sofusalbertsen** [comment]
Have made a small docker-compose script together with nginx configuration at napatech.
Will it be worth it to try to integrate that into Staci so that they all run on :80 with their respected contexts @hoeghh ?

**Comment by hoeghh** [comment]
Hi,

Yes. I was planning on making a proxy service in STACI. Just remember to put it through the hole process in STACI (which products should be proxied?, build the proxy and so on).
Let me know if you need help.

**Comment by sofusalbertsen** [comment]
Close this due to already issued in #20
